
# 配置端口
server:
  port: 8083

spring:

  #邮箱基本配置
  mail:
    # 163     smtp.163.com       端口号465或994
    host: smtp.163.com
    #发送者邮箱
    username:
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password:
    #端口号465或587
    port: 465
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
    # 这个一定要设置，否则将发送失败
    protocol: smtps



